# Generated by Django 3.2.8 on 2021-11-24 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordersapp', '0003_order_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('FM', 'Формируется'), ('STP', 'Отправлен в обработку'), ('PRD', 'Обрабатывается'), ('PD', 'Оплачен'), ('DN', 'Выполнен'), ('CN', 'Отменен')], default='FM', max_length=3),
        ),
    ]
